'use client'

interface ExportButtonProps {
  reportRef: React.RefObject<HTMLDivElement | null>
  monthLabel: string
}

export function ExportButton({ reportRef, monthLabel }: ExportButtonProps) {
  function handleExportPDF() {
    const content = reportRef.current
    if (!content) return

    const printWindow = window.open('', '_blank')
    if (!printWindow) return

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>Floin Report — ${monthLabel}</title>
          <style>
            * { margin: 0; padding: 0; box-sizing: border-box; }
            body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; padding: 40px; color: #0f172a; max-width: 600px; margin: 0 auto; }
            .header { text-align: center; margin-bottom: 32px; }
            .header h1 { font-size: 28px; background: linear-gradient(135deg, #00c896, #7c5cfc); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }
            .header p { font-size: 13px; color: #94a3b8; margin-top: 4px; }
            .content { font-size: 14px; line-height: 1.7; }
            .footer { margin-top: 40px; text-align: center; font-size: 11px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 16px; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>Floin</h1>
            <p>${monthLabel} Report</p>
          </div>
          <div class="content">${content.innerHTML}</div>
          <div class="footer">Generated by Floin · ${new Date().toLocaleDateString('en-NG')}</div>
        </body>
      </html>
    `)
    printWindow.document.close()
    printWindow.print()
  }

  function handleExportCSV() {
    const content = reportRef.current
    if (!content) return

    const rows: string[][] = [['Metric', 'Value']]
    const metrics = content.querySelectorAll('[data-metric]')
    metrics.forEach((el) => {
      const label = el.getAttribute('data-metric') || ''
      const value = el.textContent || ''
      rows.push([label, value])
    })

    const csv = rows.map((row) => row.map((cell) => `"${cell}"`).join(',')).join('\n')
    const blob = new Blob([csv], { type: 'text/csv' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `floin-report-${monthLabel.toLowerCase().replace(/\s/g, '-')}.csv`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="flex gap-1.5">
      <button
        onClick={handleExportPDF}
        className="flex items-center gap-1.5 rounded-xl bg-white px-3 py-2 text-xs font-medium text-muted-dark shadow-sm border border-border/40 transition-all hover:shadow-md hover:text-foreground active:scale-95"
      >
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" className="h-3 w-3">
          <path fillRule="evenodd" d="M4 2a1.5 1.5 0 0 0-1.5 1.5v9A1.5 1.5 0 0 0 4 14h8a1.5 1.5 0 0 0 1.5-1.5V6.621a1.5 1.5 0 0 0-.44-1.06L9.94 2.439A1.5 1.5 0 0 0 8.878 2H4Zm1 5.75A.75.75 0 0 1 5.75 7h4.5a.75.75 0 0 1 0 1.5h-4.5A.75.75 0 0 1 5 7.75Zm0 3a.75.75 0 0 1 .75-.75h4.5a.75.75 0 0 1 0 1.5h-4.5a.75.75 0 0 1-.75-.75Z" clipRule="evenodd" />
        </svg>
        PDF
      </button>
      <button
        onClick={handleExportCSV}
        className="flex items-center gap-1.5 rounded-xl bg-white px-3 py-2 text-xs font-medium text-muted-dark shadow-sm border border-border/40 transition-all hover:shadow-md hover:text-foreground active:scale-95"
      >
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" className="h-3 w-3">
          <path d="M8.75 2.75a.75.75 0 0 0-1.5 0v5.69L5.03 6.22a.75.75 0 0 0-1.06 1.06l3.5 3.5a.75.75 0 0 0 1.06 0l3.5-3.5a.75.75 0 0 0-1.06-1.06L8.75 8.44V2.75Z" />
          <path d="M3.5 9.75a.75.75 0 0 0-1.5 0v1.5A2.75 2.75 0 0 0 4.75 14h6.5A2.75 2.75 0 0 0 14 11.25v-1.5a.75.75 0 0 0-1.5 0v1.5c0 .69-.56 1.25-1.25 1.25h-6.5c-.69 0-1.25-.56-1.25-1.25v-1.5Z" />
        </svg>
        CSV
      </button>
    </div>
  )
}
